kind: pipeline
name: default

steps:
- name: unit_tests
  image: ubuntu:18.04
  commands:
    - DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y python3 openjdk-11-jdk-headless
    - ./gradlew -s check

- name: system_tests
  image: ubuntu:18.04
  commands:
    - DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y python3 openjdk-11-jdk-headless
    - ./gradlew -s assemble
    - ./gradlew -s jar
    - ./gradlew -s check
    - ./gradlew publishToMavenLocal
    - cd tests
    - chmod +x run_system_tests.py
    - cd jars
    - bash build.sh
    - cd ..
    - python3 ./run_system_tests.py --build-first
