dist: xenial
language: java

before_install:
- sudo apt-get update
- sudo apt-get install python3

after_install:
- ./gradlew boolJar

script:
- cd tests
- chmod +x run_system_tests.py
- cd jars
- bash build.sh
- cd ..
- python3 ./run_system_tests.py --build-first  --taint_type=bool
- python3 ./run_system_tests.py --build-first  --taint_type=range
