dist: xenial
language: java

jdk:
  - openjdk11

before_install:
- sudo apt-get update
- sudo apt-get install python3

install: true

script:
- $TRAVIS_BUILD_DIR/install-jdk.sh --install openjdk11 --target $JAVA_HOME
- java -version
- ./gradlew -s assemble
- ./gradlew -s check
- ./gradlew publishToMavenLocal
- cd tests
- chmod +x run_system_tests.py
- cd jars
- bash build.sh
- cd ..
- python3 ./run_system_tests.py --build-first  --taint_type=boolean
