dist: bionic
language: java

jdk:
  - openjdk10
  - openjdk11
  - openjdk15

before_install:
- sudo apt-get update
- sudo apt-get install python3

install: true



script:
- ./gradlew -s assemble
- ./gradlew -s check
- ./gradlew publishToMavenLocal
- cd tests
- chmod +x run_system_tests.py
- cd jars
- bash build.sh
- cd ..
- python3 ./run_system_tests.py --build-first  --taint_type=boolean
