name: Java CI with Gradle

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    strategy:
      matrix:
        distribution: ['temurin', 'zulu', 'microsoft', 'corretto', 'semeru', 'dragonwell', 'sapmachine']
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: ${{ matrix.distribution }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: ./gradlew clean check shadowJar

  system-tests:
    strategy:
      matrix:
        distribution: ['temurin', 'zulu', 'microsoft', 'corretto', 'semeru', 'dragonwell', 'sapmachine']
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: ${{ matrix.distribution }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: ./gradlew shadowJar

    - name: Run system tests
      working-directory: ./tests
      run: python run_system_tests.py --build-first
