name: Java CI with Gradle

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    strategy:
      matrix:
        distribution: ['temurin', 'zulu', 'microsoft', 'corretto', 'semeru', 'dragonwell']
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: ${{ matrix.distribution }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: ./gradlew clean check shadowJar

    - name: Run system tests
      working-directory: ./tests
      run: python run_system_tests.py --build-first
